- name: Create docker.service.d directory
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory
- name: copy http-proxy
  template:
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
- name: Enable and check Docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_docker
- name: Copy ca file
  copy: src=docker_registry_proxy.crt dest=/usr/share/ca-certificates/docker_registry_proxy.crt  
- name: Adding ca certificate
  lineinfile:
    dest: /etc/ca-certificates.conf
    state: present
    line: docker_registry_proxy.crt
- name: Update ca certificate
  shell: 'update-ca-certificates --fresh'
