- name: Install the package "docker"
  apt:
    name: docker.io
    state: present
- name: copy daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
- name: Enable and check Docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_docker
